FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /orderservice

COPY . .
RUN dotnet restore
RUN dotnet publish -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:10.0
WORKDIR /app

COPY --from=build /app/publish/ .

ENTRYPOINT ["dotnet", "OrderService.dll"]