services:
  customer_service:
    build: ./customerservice
    container_name: SEN300CustomerService
    ports:
      - "8002:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=customers;Username=postgres_user;Password=postgres!
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - sen300_network
    restart: always

  postgres:
    image: postgres:16
    container_name: SEN300CustomerServiceDBPostgres
    environment:
      POSTGRES_DB: customers
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres!
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres_user -d customers"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - sen300_network
    restart: always
  
  auth_service:
    build: ./authservice
    container_name: SEN300AuthService
    ports:
      - "8003:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      - customer_service
    networks:
      - sen300_network
    restart: always

volumes:
  postgres_data:

networks:
  sen300_network:
    external: true